site_name: karpiu
site_url: https://edwinng.com/karpiu/

nav:
  - Home: index.md
  - Quickstart: ./examples/quickstart.ipynb
  - More Examples:
    - Attribution: ./examples/attribution.ipynb
    - Adstock: ./examples/adstock.ipynb
  - Optimization:
    - Target Maximization: ./examples/target_max.ipynb
    - Net Returns Maximization: ./examples/net_returns_max.ipynb

plugins:
  - mkdocs-jupyter