site_name: karpiu
site_url: https://edwinng.com/karpiu/

nav:
  - Home: index.md
  - Examples: 
    - Quickstart: ./examples/quickstart.ipynb
    - Attribution: ./examples/attribution.ipynb
    - Optimization: ./examples/optimization.ipynb

plugins:
  - mkdocs-jupyter