name: lint and test

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check --verbose --color"
          jupyter: false

  build:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          pip install -U pip
          pip install -U setuptools
          pip install -r requirements.txt
          python -m pip install -e .
      - name: Test and create core models in pytest
        run: pytest -vs tests/tests_first/  --cov=karpiu --cov-report term-missing
      - name: Test the rest in pytest
        run: pytest -vs tests/tests_rest/  --cov=karpiu --cov-report term-missing