name: pages
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and deploy pages
        run: |
          sudo apt-get install libxml2-dev libxslt-dev
          pip install --upgrade pip
          pip install -r requirements-docs.txt
          mkdocs build
    